version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ChallengeUser
      POSTGRES_PASSWORD: Challenge1234
      POSTGRES_DB: ChallengeDB
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432

volumes:
  pgdata: